import React from "react";
import {
  Box,
  Card,
  CardContent,
  List,
  ListItem,
  ListItemText,
  Typography,
} from "@mui/material";

export const ForStakers = () => {
  return (
    <Card
      sx={{
        maxWidth: "400px",
      }}
    >
      <CardContent>
        <Typography variant="h5">For Crypto Users</Typography>
        <List>
          <ListItem>
            <ListItemText
              primary="Fight climate change."
              secondary="Directly help the fight against climate change by incentivising growth in the solar industry."
            />
          </ListItem>
          <ListItem>
            <ListItemText
              primary="Earn tokens!"
              secondary="Earn SOLEIL tokens based on the amount of energy generated by registered solar plants. The more they generate the more you earn!"
            />
          </ListItem>
        </List>
      </CardContent>
    </Card>
  );
};
