import { Box } from "@mui/material";
import Stat from "./Stat";

export const LeftStats = ({ stats }: any) => {
  return (
    <Box
      sx={{
        height: "100%",
        maxWidth: "220px",
        display: "flex",
        flexDirection: "column",
        // alignItems: "flex-end",
        justifyContent: "center",
      }}
    >
      <Stat
        header="Total energy generated by sites today"
        value={`${
          stats ? Math.floor(stats.todayEnergyGenerated / 1000) : 0
        }kWh`}
      />
      <Stat header="Projected DAI distributions for today" value={100} />
      <Stat header="Projected SLL generation for today" value={65} />
    </Box>
  );
};

export const RightStats = ({ stats }: any) => {
  return (
    <Box
      sx={{
        height: "100%",
        maxWidth: "200px",
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        // alignItems: "flex-start",
      }}
    >
      <Stat
        header="Total energy generated by sites overall"
        value={`${
          stats ? Math.floor(stats.allTimeEnergyGenerated / 1000) : 0
        }kWh`}
      />
      <Stat header="Total overall DAI distributions" value={800} />
      <Stat header="Total SLL generated" value={19} />
    </Box>
  );
};
